version: "3.3"
services:
    mongodb:
        container_name: mongo
        image: mongo:4.2
        restart: always

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile.backend
        restart: always
        depends_on:
            - mongodb
        ports:
            - "7000:80"
        environment:
            - Workers=http://worker1/;http://worker2/
            - MongoDBConnectionString=mongodb://mongodb:27017/matroos
            - MongoDBDatabaseName=matroos
        healthcheck:
            test: curl --fail -s http://localhost/health || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

    worker1:
        container_name: worker1
        build:
            context: .
            dockerfile: Dockerfile.worker
        restart: always
        ports:
            - "7001:80"
        healthcheck:
            test: curl --fail -s http://localhost/health || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

    worker2:
        container_name: worker2
        build:
            context: .
            dockerfile: Dockerfile.worker
        restart: always
        ports:
            - "7002:80"
        healthcheck:
            test: curl --fail -s http://localhost/health || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
